### ISSUE TITLE
Unify binary, repo and image naming

### ISSUE THREAD

**Issue by tnozicka** [scylladb/local-csi-driver#39]
We should unify the packages, binary and image name for consistency.

At this point the difference is confusing (caused by historical reasons when requesting the repo name):
repo name: `github.com/scylladb/k8s-local-volume-provisioner`
image name:  `docker.io/scylladb/k8s-local-volume-provisioner`
binary name: `local-csi-driver`

**Comment by zimnx** [comment]
I collected pros and cons behind few options we discussed, here's a summary:

---

Change k8s-local-volume-provisioner to local-csi-driver
+ (pro) name convention matches other drivers available
+ (pro) simple user update, it requires changing an image used in manifests. Namespace and object names stay the same.

What needs to be done afterwards:
* rename the Github repo
* create new quay/docker repo, gain access for CI jobs through IT/Tomas
* update all jobs in CI to use new name

Change local-csi-driver to k8s-local-volume-provisioner
+ (pro) name convention matches kubernetes-sigs local-static-volume-provisioner
* (con) conterargument about above, this project doesn't provide any provisioner implementation, it's being used as a dependency
* (con) k8s prefix might be an issue, as drivers are designed to be run not only on kubernetes - although there are no plans for having support for other orchestrators
* (con) update requires manually deleting namespace first and only then applying new manifests

What needs to be done afterwards:
* rename binary and names in manifests in CI, Operator and repo itself

Change k8s-local-volume-provisioner to scylladb-local-csi(-driver)
+ (pro) scylla prefix prevents collision with other solutions
* (con) nothing is related to scylla, we are just the maintainers
* (con) scylla prefix may be confusing, users can use GCP, AWS CSI or other drivers and run scylla without known issues

What needs to be done afterwards:
* rename Github repo
* create new quay/docker repo, gain access for CI jobs through IT/Tomas
* update all jobs in CI to use new name
* rename binary and names in manifests in CI, Operator and repo itself

---

I had a meeting with @ylebi where we discussed them, and we are align on opting to the first option. 
@tnozicka what do you think?
