### ISSUE TITLE
Create new docker/quay repositories for local-csi-driver

### ISSUE THREAD

**Issue by ylebi** [scylladb/local-csi-driver#54]
## Context 

As part of https://github.com/scylladb/k8s-local-volume-provisioner/issues/39, we need to create new docker.io / quay.io repositories.

## What's need to be done?

Create the following on public docker.io and quay.io repositories:
- `scylladb/local-csi-driver` 
- `scylladb/local-csi-driver-tests`

**Comment by tnozicka** [comment]
quay repo is pre-created https://quay.io/repository/scylladb/local-csi-driver (but we need to update the CI jobs when the repo is renamed

**Comment by tnozicka** [comment]
and https://quay.io/repository/scylladb/local-csi-driver-tests

**Comment by ylebi** [comment]
@yaronkaikov can you open the same for docker.io?

**Comment by yaronkaikov** [comment]
> @yaronkaikov can you open the same for docker.io?

https://hub.docker.com/repository/docker/scylladb/local-csi-driver
done

**Comment by ylebi** [comment]
Done

**Comment by zimnx** [comment]
@yaronkaikov we also need `scylladb/local-csi-driver-tests` in docker hub

**Comment by ylebi** [comment]
> @yaronkaikov we also need `scylladb/local-csi-driver-tests` in docker hub

Thanks for catching that @zimnx.
@tnozicka we need that in quay.io as well just to have it aligned with what we already had before the change.

**Comment by zimnx** [comment]
Thanks! 
Quay is already there: https://quay.io/repository/scylladb/local-csi-driver-tests
